external table
StarRocks/docs pull request #84
Opened 2022-05-06 09:27 UTC by evelynzhaojie

added the “Apache Iceberg external table” section and optimized original English version

2022-05-11 08:30 UTC, EsoragotoSpirit requested changes

2022-05-11 08:30 UTC, EsoragotoSpirit commented on using_starrocks/External_table.md
>  ~~~sql
Query the total number of rows of `profile_wos_p7`

~~~sql
select count(*) from profile_wos_p7;
~~~

2022-05-11 08:36 UTC, evelynzhaojie commented on using_starrocks/External_table.md
> +# External tables
以前在阿里云习惯用sentence case，我看aws或者竞品，也很多用sentence case的，我们后面把这个写到规范里。

2022-05-15 23:40 UTC, evelynzhaojie commented on using_starrocks/External_table.md
> +select count(*) from iceberg_tbl;
代码里的规范我们暂时不改哈，除非时错误

2022-07-12 07:47 UTC, closed without merging